[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_autosave = 1
    let g:rust_doc#define_map_K = 0
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
    set hidden
    let g:racer_cmd = "~/.cargo/bin/racer"
    let g:racer_experimental_completer = 1
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

